package com.jwebcoder.grocerystatic.domain;

import java.util.Date;

public class ClientInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.SESSION
     *
     * @mbg.generated
     */
    private String session;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.LAST_ACCESSED_TIME
     *
     * @mbg.generated
     */
    private String lastAccessedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.VISITOR_IP
     *
     * @mbg.generated
     */
    private String visitorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.VISITOR_BROWSER_VERSION
     *
     * @mbg.generated
     */
    private String visitorBrowserVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.VISITOR_SYSTEM_VERSION
     *
     * @mbg.generated
     */
    private String visitorSystemVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.VISITOR_HOST_NAME
     *
     * @mbg.generated
     */
    private String visitorHostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.VISITOR_MAC_ADDRESS
     *
     * @mbg.generated
     */
    private String visitorMacAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT_INFO.CREATE_DATETIME
     *
     * @mbg.generated
     */
    private Date createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.ID
     *
     * @return the value of CLIENT_INFO.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.ID
     *
     * @param id the value for CLIENT_INFO.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.VERSION
     *
     * @return the value of CLIENT_INFO.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.VERSION
     *
     * @param version the value for CLIENT_INFO.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.SESSION
     *
     * @return the value of CLIENT_INFO.SESSION
     *
     * @mbg.generated
     */
    public String getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.SESSION
     *
     * @param session the value for CLIENT_INFO.SESSION
     *
     * @mbg.generated
     */
    public void setSession(String session) {
        this.session = session == null ? null : session.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.LAST_ACCESSED_TIME
     *
     * @return the value of CLIENT_INFO.LAST_ACCESSED_TIME
     *
     * @mbg.generated
     */
    public String getLastAccessedTime() {
        return lastAccessedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.LAST_ACCESSED_TIME
     *
     * @param lastAccessedTime the value for CLIENT_INFO.LAST_ACCESSED_TIME
     *
     * @mbg.generated
     */
    public void setLastAccessedTime(String lastAccessedTime) {
        this.lastAccessedTime = lastAccessedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.VISITOR_IP
     *
     * @return the value of CLIENT_INFO.VISITOR_IP
     *
     * @mbg.generated
     */
    public String getVisitorIp() {
        return visitorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.VISITOR_IP
     *
     * @param visitorIp the value for CLIENT_INFO.VISITOR_IP
     *
     * @mbg.generated
     */
    public void setVisitorIp(String visitorIp) {
        this.visitorIp = visitorIp == null ? null : visitorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.VISITOR_BROWSER_VERSION
     *
     * @return the value of CLIENT_INFO.VISITOR_BROWSER_VERSION
     *
     * @mbg.generated
     */
    public String getVisitorBrowserVersion() {
        return visitorBrowserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.VISITOR_BROWSER_VERSION
     *
     * @param visitorBrowserVersion the value for CLIENT_INFO.VISITOR_BROWSER_VERSION
     *
     * @mbg.generated
     */
    public void setVisitorBrowserVersion(String visitorBrowserVersion) {
        this.visitorBrowserVersion = visitorBrowserVersion == null ? null : visitorBrowserVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.VISITOR_SYSTEM_VERSION
     *
     * @return the value of CLIENT_INFO.VISITOR_SYSTEM_VERSION
     *
     * @mbg.generated
     */
    public String getVisitorSystemVersion() {
        return visitorSystemVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.VISITOR_SYSTEM_VERSION
     *
     * @param visitorSystemVersion the value for CLIENT_INFO.VISITOR_SYSTEM_VERSION
     *
     * @mbg.generated
     */
    public void setVisitorSystemVersion(String visitorSystemVersion) {
        this.visitorSystemVersion = visitorSystemVersion == null ? null : visitorSystemVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.VISITOR_HOST_NAME
     *
     * @return the value of CLIENT_INFO.VISITOR_HOST_NAME
     *
     * @mbg.generated
     */
    public String getVisitorHostName() {
        return visitorHostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.VISITOR_HOST_NAME
     *
     * @param visitorHostName the value for CLIENT_INFO.VISITOR_HOST_NAME
     *
     * @mbg.generated
     */
    public void setVisitorHostName(String visitorHostName) {
        this.visitorHostName = visitorHostName == null ? null : visitorHostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.VISITOR_MAC_ADDRESS
     *
     * @return the value of CLIENT_INFO.VISITOR_MAC_ADDRESS
     *
     * @mbg.generated
     */
    public String getVisitorMacAddress() {
        return visitorMacAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.VISITOR_MAC_ADDRESS
     *
     * @param visitorMacAddress the value for CLIENT_INFO.VISITOR_MAC_ADDRESS
     *
     * @mbg.generated
     */
    public void setVisitorMacAddress(String visitorMacAddress) {
        this.visitorMacAddress = visitorMacAddress == null ? null : visitorMacAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT_INFO.CREATE_DATETIME
     *
     * @return the value of CLIENT_INFO.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT_INFO.CREATE_DATETIME
     *
     * @param createDatetime the value for CLIENT_INFO.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }
}