package com.jwebcoder.grocerystatic.domain;

public class InstationSenderMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.SENDER_USER_ID
     *
     * @mbg.generated
     */
    private Integer senderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.RECEIVER_USER_ID
     *
     * @mbg.generated
     */
    private Integer receiverUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.INSTATION_SENDER_CONTENT_ID
     *
     * @mbg.generated
     */
    private Integer instationSenderContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.READ_FLAG
     *
     * @mbg.generated
     */
    private String readFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.CREATE_DATETIME
     *
     * @mbg.generated
     */
    private String createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.CUSTOM1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.CUSTOM2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.CUSTOM3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.CUSTOM4
     *
     * @mbg.generated
     */
    private String custom4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTATION_SENDER_MAPPING.CUSTOM5
     *
     * @mbg.generated
     */
    private String custom5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.ID
     *
     * @return the value of INSTATION_SENDER_MAPPING.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.ID
     *
     * @param id the value for INSTATION_SENDER_MAPPING.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.VERSION
     *
     * @return the value of INSTATION_SENDER_MAPPING.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.VERSION
     *
     * @param version the value for INSTATION_SENDER_MAPPING.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.SENDER_USER_ID
     *
     * @return the value of INSTATION_SENDER_MAPPING.SENDER_USER_ID
     *
     * @mbg.generated
     */
    public Integer getSenderUserId() {
        return senderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.SENDER_USER_ID
     *
     * @param senderUserId the value for INSTATION_SENDER_MAPPING.SENDER_USER_ID
     *
     * @mbg.generated
     */
    public void setSenderUserId(Integer senderUserId) {
        this.senderUserId = senderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.RECEIVER_USER_ID
     *
     * @return the value of INSTATION_SENDER_MAPPING.RECEIVER_USER_ID
     *
     * @mbg.generated
     */
    public Integer getReceiverUserId() {
        return receiverUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.RECEIVER_USER_ID
     *
     * @param receiverUserId the value for INSTATION_SENDER_MAPPING.RECEIVER_USER_ID
     *
     * @mbg.generated
     */
    public void setReceiverUserId(Integer receiverUserId) {
        this.receiverUserId = receiverUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.INSTATION_SENDER_CONTENT_ID
     *
     * @return the value of INSTATION_SENDER_MAPPING.INSTATION_SENDER_CONTENT_ID
     *
     * @mbg.generated
     */
    public Integer getInstationSenderContentId() {
        return instationSenderContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.INSTATION_SENDER_CONTENT_ID
     *
     * @param instationSenderContentId the value for INSTATION_SENDER_MAPPING.INSTATION_SENDER_CONTENT_ID
     *
     * @mbg.generated
     */
    public void setInstationSenderContentId(Integer instationSenderContentId) {
        this.instationSenderContentId = instationSenderContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.READ_FLAG
     *
     * @return the value of INSTATION_SENDER_MAPPING.READ_FLAG
     *
     * @mbg.generated
     */
    public String getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.READ_FLAG
     *
     * @param readFlag the value for INSTATION_SENDER_MAPPING.READ_FLAG
     *
     * @mbg.generated
     */
    public void setReadFlag(String readFlag) {
        this.readFlag = readFlag == null ? null : readFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.CREATE_DATETIME
     *
     * @return the value of INSTATION_SENDER_MAPPING.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public String getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.CREATE_DATETIME
     *
     * @param createDatetime the value for INSTATION_SENDER_MAPPING.CREATE_DATETIME
     *
     * @mbg.generated
     */
    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime == null ? null : createDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.CUSTOM1
     *
     * @return the value of INSTATION_SENDER_MAPPING.CUSTOM1
     *
     * @mbg.generated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.CUSTOM1
     *
     * @param custom1 the value for INSTATION_SENDER_MAPPING.CUSTOM1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.CUSTOM2
     *
     * @return the value of INSTATION_SENDER_MAPPING.CUSTOM2
     *
     * @mbg.generated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.CUSTOM2
     *
     * @param custom2 the value for INSTATION_SENDER_MAPPING.CUSTOM2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.CUSTOM3
     *
     * @return the value of INSTATION_SENDER_MAPPING.CUSTOM3
     *
     * @mbg.generated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.CUSTOM3
     *
     * @param custom3 the value for INSTATION_SENDER_MAPPING.CUSTOM3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.CUSTOM4
     *
     * @return the value of INSTATION_SENDER_MAPPING.CUSTOM4
     *
     * @mbg.generated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.CUSTOM4
     *
     * @param custom4 the value for INSTATION_SENDER_MAPPING.CUSTOM4
     *
     * @mbg.generated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTATION_SENDER_MAPPING.CUSTOM5
     *
     * @return the value of INSTATION_SENDER_MAPPING.CUSTOM5
     *
     * @mbg.generated
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTATION_SENDER_MAPPING.CUSTOM5
     *
     * @param custom5 the value for INSTATION_SENDER_MAPPING.CUSTOM5
     *
     * @mbg.generated
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }
}