package com.jwebcoder.grocerystatic.domain;

public class MessageBoardTitleMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.ORDER_NUM
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CREATE_DATETIME
     *
     * @mbggenerated
     */
    private String createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM1
     *
     * @mbggenerated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM2
     *
     * @mbggenerated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM3
     *
     * @mbggenerated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM4
     *
     * @mbggenerated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM5
     *
     * @mbggenerated
     */
    private String custom5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.ID
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.ID
     *
     * @param id the value for MESSAGE_BOARD_TITLE_MESSAGE.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.VERSION
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.VERSION
     *
     * @param version the value for MESSAGE_BOARD_TITLE_MESSAGE.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CONTENT
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CONTENT
     *
     * @param content the value for MESSAGE_BOARD_TITLE_MESSAGE.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.ORDER_NUM
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.ORDER_NUM
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.ORDER_NUM
     *
     * @param orderNum the value for MESSAGE_BOARD_TITLE_MESSAGE.ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CREATE_DATETIME
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CREATE_DATETIME
     *
     * @mbggenerated
     */
    public String getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CREATE_DATETIME
     *
     * @param createDatetime the value for MESSAGE_BOARD_TITLE_MESSAGE.CREATE_DATETIME
     *
     * @mbggenerated
     */
    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime == null ? null : createDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM1
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM1
     *
     * @mbggenerated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM1
     *
     * @param custom1 the value for MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM1
     *
     * @mbggenerated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM2
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM2
     *
     * @mbggenerated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM2
     *
     * @param custom2 the value for MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM2
     *
     * @mbggenerated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM3
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM3
     *
     * @mbggenerated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM3
     *
     * @param custom3 the value for MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM3
     *
     * @mbggenerated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM4
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM4
     *
     * @mbggenerated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM4
     *
     * @param custom4 the value for MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM4
     *
     * @mbggenerated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM5
     *
     * @return the value of MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM5
     *
     * @mbggenerated
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM5
     *
     * @param custom5 the value for MESSAGE_BOARD_TITLE_MESSAGE.CUSTOM5
     *
     * @mbggenerated
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }
}