package com.jwebcoder.grocerystatic.domain;

public class PersonalMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.MENU_ITEM_NAME
     *
     * @mbggenerated
     */
    private String menuItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.INTERLINKAGE
     *
     * @mbggenerated
     */
    private String interlinkage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.LINK_MATCHING
     *
     * @mbggenerated
     */
    private String linkMatching;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.ORDER_NUMBER
     *
     * @mbggenerated
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.CUSTOM1
     *
     * @mbggenerated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.CUSTOM2
     *
     * @mbggenerated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.CUSTOM3
     *
     * @mbggenerated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.CUSTOM4
     *
     * @mbggenerated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_MENU.CUSTOM5
     *
     * @mbggenerated
     */
    private String custom5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.ID
     *
     * @return the value of PERSONAL_MENU.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.ID
     *
     * @param id the value for PERSONAL_MENU.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.VERSION
     *
     * @return the value of PERSONAL_MENU.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.VERSION
     *
     * @param version the value for PERSONAL_MENU.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.MENU_ITEM_NAME
     *
     * @return the value of PERSONAL_MENU.MENU_ITEM_NAME
     *
     * @mbggenerated
     */
    public String getMenuItemName() {
        return menuItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.MENU_ITEM_NAME
     *
     * @param menuItemName the value for PERSONAL_MENU.MENU_ITEM_NAME
     *
     * @mbggenerated
     */
    public void setMenuItemName(String menuItemName) {
        this.menuItemName = menuItemName == null ? null : menuItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.INTERLINKAGE
     *
     * @return the value of PERSONAL_MENU.INTERLINKAGE
     *
     * @mbggenerated
     */
    public String getInterlinkage() {
        return interlinkage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.INTERLINKAGE
     *
     * @param interlinkage the value for PERSONAL_MENU.INTERLINKAGE
     *
     * @mbggenerated
     */
    public void setInterlinkage(String interlinkage) {
        this.interlinkage = interlinkage == null ? null : interlinkage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.LINK_MATCHING
     *
     * @return the value of PERSONAL_MENU.LINK_MATCHING
     *
     * @mbggenerated
     */
    public String getLinkMatching() {
        return linkMatching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.LINK_MATCHING
     *
     * @param linkMatching the value for PERSONAL_MENU.LINK_MATCHING
     *
     * @mbggenerated
     */
    public void setLinkMatching(String linkMatching) {
        this.linkMatching = linkMatching == null ? null : linkMatching.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.ORDER_NUMBER
     *
     * @return the value of PERSONAL_MENU.ORDER_NUMBER
     *
     * @mbggenerated
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.ORDER_NUMBER
     *
     * @param orderNumber the value for PERSONAL_MENU.ORDER_NUMBER
     *
     * @mbggenerated
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.CUSTOM1
     *
     * @return the value of PERSONAL_MENU.CUSTOM1
     *
     * @mbggenerated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.CUSTOM1
     *
     * @param custom1 the value for PERSONAL_MENU.CUSTOM1
     *
     * @mbggenerated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.CUSTOM2
     *
     * @return the value of PERSONAL_MENU.CUSTOM2
     *
     * @mbggenerated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.CUSTOM2
     *
     * @param custom2 the value for PERSONAL_MENU.CUSTOM2
     *
     * @mbggenerated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.CUSTOM3
     *
     * @return the value of PERSONAL_MENU.CUSTOM3
     *
     * @mbggenerated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.CUSTOM3
     *
     * @param custom3 the value for PERSONAL_MENU.CUSTOM3
     *
     * @mbggenerated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.CUSTOM4
     *
     * @return the value of PERSONAL_MENU.CUSTOM4
     *
     * @mbggenerated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.CUSTOM4
     *
     * @param custom4 the value for PERSONAL_MENU.CUSTOM4
     *
     * @mbggenerated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_MENU.CUSTOM5
     *
     * @return the value of PERSONAL_MENU.CUSTOM5
     *
     * @mbggenerated
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_MENU.CUSTOM5
     *
     * @param custom5 the value for PERSONAL_MENU.CUSTOM5
     *
     * @mbggenerated
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }
}