package com.jwebcoder.grocerystatic.domain;

public class PersonalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.AVATOR
     *
     * @mbggenerated
     */
    private Integer avator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.COMMTS
     *
     * @mbggenerated
     */
    private String commts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.CUSTOM1
     *
     * @mbggenerated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.CUSTOM2
     *
     * @mbggenerated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.CUSTOM3
     *
     * @mbggenerated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.CUSTOM4
     *
     * @mbggenerated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_INFO.CUSTOM5
     *
     * @mbggenerated
     */
    private String custom5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.ID
     *
     * @return the value of PERSONAL_INFO.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.ID
     *
     * @param id the value for PERSONAL_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.VERSION
     *
     * @return the value of PERSONAL_INFO.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.VERSION
     *
     * @param version the value for PERSONAL_INFO.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.USER_ID
     *
     * @return the value of PERSONAL_INFO.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.USER_ID
     *
     * @param userId the value for PERSONAL_INFO.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.AVATOR
     *
     * @return the value of PERSONAL_INFO.AVATOR
     *
     * @mbggenerated
     */
    public Integer getAvator() {
        return avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.AVATOR
     *
     * @param avator the value for PERSONAL_INFO.AVATOR
     *
     * @mbggenerated
     */
    public void setAvator(Integer avator) {
        this.avator = avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.COMMTS
     *
     * @return the value of PERSONAL_INFO.COMMTS
     *
     * @mbggenerated
     */
    public String getCommts() {
        return commts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.COMMTS
     *
     * @param commts the value for PERSONAL_INFO.COMMTS
     *
     * @mbggenerated
     */
    public void setCommts(String commts) {
        this.commts = commts == null ? null : commts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.CUSTOM1
     *
     * @return the value of PERSONAL_INFO.CUSTOM1
     *
     * @mbggenerated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.CUSTOM1
     *
     * @param custom1 the value for PERSONAL_INFO.CUSTOM1
     *
     * @mbggenerated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.CUSTOM2
     *
     * @return the value of PERSONAL_INFO.CUSTOM2
     *
     * @mbggenerated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.CUSTOM2
     *
     * @param custom2 the value for PERSONAL_INFO.CUSTOM2
     *
     * @mbggenerated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.CUSTOM3
     *
     * @return the value of PERSONAL_INFO.CUSTOM3
     *
     * @mbggenerated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.CUSTOM3
     *
     * @param custom3 the value for PERSONAL_INFO.CUSTOM3
     *
     * @mbggenerated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.CUSTOM4
     *
     * @return the value of PERSONAL_INFO.CUSTOM4
     *
     * @mbggenerated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.CUSTOM4
     *
     * @param custom4 the value for PERSONAL_INFO.CUSTOM4
     *
     * @mbggenerated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_INFO.CUSTOM5
     *
     * @return the value of PERSONAL_INFO.CUSTOM5
     *
     * @mbggenerated
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_INFO.CUSTOM5
     *
     * @param custom5 the value for PERSONAL_INFO.CUSTOM5
     *
     * @mbggenerated
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }
}