package com.jwebcoder.grocerystatic.domain;

public class PhotographyPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.ID
     *
     * @mbggenerated
     */
    private Integer id = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.COMMENTS
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.CUSTOM1
     *
     * @mbggenerated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.CUSTOM2
     *
     * @mbggenerated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.CUSTOM3
     *
     * @mbggenerated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.CUSTOM4
     *
     * @mbggenerated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.CUSTOM5
     *
     * @mbggenerated
     */
    private String custom5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.PHOTO
     *
     * @mbggenerated
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.ID
     *
     * @return the value of PHOTOGRAPHY_PHOTO.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.ID
     *
     * @param id the value for PHOTOGRAPHY_PHOTO.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.VERSION
     *
     * @return the value of PHOTOGRAPHY_PHOTO.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.VERSION
     *
     * @param version the value for PHOTOGRAPHY_PHOTO.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.TYPE
     *
     * @return the value of PHOTOGRAPHY_PHOTO.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.TYPE
     *
     * @param type the value for PHOTOGRAPHY_PHOTO.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.COMMENTS
     *
     * @return the value of PHOTOGRAPHY_PHOTO.COMMENTS
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.COMMENTS
     *
     * @param comments the value for PHOTOGRAPHY_PHOTO.COMMENTS
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM1
     *
     * @return the value of PHOTOGRAPHY_PHOTO.CUSTOM1
     *
     * @mbggenerated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM1
     *
     * @param custom1 the value for PHOTOGRAPHY_PHOTO.CUSTOM1
     *
     * @mbggenerated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM2
     *
     * @return the value of PHOTOGRAPHY_PHOTO.CUSTOM2
     *
     * @mbggenerated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM2
     *
     * @param custom2 the value for PHOTOGRAPHY_PHOTO.CUSTOM2
     *
     * @mbggenerated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM3
     *
     * @return the value of PHOTOGRAPHY_PHOTO.CUSTOM3
     *
     * @mbggenerated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM3
     *
     * @param custom3 the value for PHOTOGRAPHY_PHOTO.CUSTOM3
     *
     * @mbggenerated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM4
     *
     * @return the value of PHOTOGRAPHY_PHOTO.CUSTOM4
     *
     * @mbggenerated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM4
     *
     * @param custom4 the value for PHOTOGRAPHY_PHOTO.CUSTOM4
     *
     * @mbggenerated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM5
     *
     * @return the value of PHOTOGRAPHY_PHOTO.CUSTOM5
     *
     * @mbggenerated
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.CUSTOM5
     *
     * @param custom5 the value for PHOTOGRAPHY_PHOTO.CUSTOM5
     *
     * @mbggenerated
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHOTOGRAPHY_PHOTO.PHOTO
     *
     * @return the value of PHOTOGRAPHY_PHOTO.PHOTO
     *
     * @mbggenerated
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHOTOGRAPHY_PHOTO.PHOTO
     *
     * @param photo the value for PHOTOGRAPHY_PHOTO.PHOTO
     *
     * @mbggenerated
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}