package com.jwebcoder.grocerystatic.domain;

public class SharingImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.CREATE_DATETIME
     *
     * @mbggenerated
     */
    private String createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.CUSTOM1
     *
     * @mbggenerated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.CUSTOM2
     *
     * @mbggenerated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.CUSTOM3
     *
     * @mbggenerated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.CUSTOM4
     *
     * @mbggenerated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.CUSTOM5
     *
     * @mbggenerated
     */
    private String custom5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARING_IMAGES.PHOTO
     *
     * @mbggenerated
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.ID
     *
     * @return the value of SHARING_IMAGES.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.ID
     *
     * @param id the value for SHARING_IMAGES.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.VERSION
     *
     * @return the value of SHARING_IMAGES.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.VERSION
     *
     * @param version the value for SHARING_IMAGES.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.TYPE
     *
     * @return the value of SHARING_IMAGES.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.TYPE
     *
     * @param type the value for SHARING_IMAGES.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.CREATE_DATETIME
     *
     * @return the value of SHARING_IMAGES.CREATE_DATETIME
     *
     * @mbggenerated
     */
    public String getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.CREATE_DATETIME
     *
     * @param createDatetime the value for SHARING_IMAGES.CREATE_DATETIME
     *
     * @mbggenerated
     */
    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime == null ? null : createDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.CUSTOM1
     *
     * @return the value of SHARING_IMAGES.CUSTOM1
     *
     * @mbggenerated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.CUSTOM1
     *
     * @param custom1 the value for SHARING_IMAGES.CUSTOM1
     *
     * @mbggenerated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.CUSTOM2
     *
     * @return the value of SHARING_IMAGES.CUSTOM2
     *
     * @mbggenerated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.CUSTOM2
     *
     * @param custom2 the value for SHARING_IMAGES.CUSTOM2
     *
     * @mbggenerated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.CUSTOM3
     *
     * @return the value of SHARING_IMAGES.CUSTOM3
     *
     * @mbggenerated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.CUSTOM3
     *
     * @param custom3 the value for SHARING_IMAGES.CUSTOM3
     *
     * @mbggenerated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.CUSTOM4
     *
     * @return the value of SHARING_IMAGES.CUSTOM4
     *
     * @mbggenerated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.CUSTOM4
     *
     * @param custom4 the value for SHARING_IMAGES.CUSTOM4
     *
     * @mbggenerated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.CUSTOM5
     *
     * @return the value of SHARING_IMAGES.CUSTOM5
     *
     * @mbggenerated
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.CUSTOM5
     *
     * @param custom5 the value for SHARING_IMAGES.CUSTOM5
     *
     * @mbggenerated
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARING_IMAGES.PHOTO
     *
     * @return the value of SHARING_IMAGES.PHOTO
     *
     * @mbggenerated
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARING_IMAGES.PHOTO
     *
     * @param photo the value for SHARING_IMAGES.PHOTO
     *
     * @mbggenerated
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}